=== karmasta13/Academics/Karmasta Music Store/karmastaMusic.dtd
<!ELEMENT Store (Header, Songs, Footer)>

<!ELEMENT Header (StoreLogo, Name, Slogan, About)>
<!ELEMENT StoreLogo (img)>
<!ELEMENT img (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Slogan (#PCDATA)>
<!ELEMENT About (#PCDATA)>


<!ELEMENT Songs (Song+)>
<!ELEMENT Song (CoverArt, SongDescription, AlbumDescription)>
<!ELEMENT CoverArt (img)>

<!ELEMENT SongDescription (Title, Artist, FeaturedArtist*,ReleaseYear, Writer+, Director*, Award?)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Artist (#PCDATA)>
<!ELEMENT ReleaseYear (#PCDATA)>
<!ELEMENT FeaturedArtist (#PCDATA)>
<!ELEMENT Writer (#PCDATA)>
<!ELEMENT Director (#PCDATA)>
<!ELEMENT Award (#PCDATA)>

<!ELEMENT AlbumDescription (Album, Comment?, Rating?, Producer+, RecordLabel+, Price)>
<!ELEMENT Album (#PCDATA)>
<!ELEMENT Comment (#PCDATA)>
<!ELEMENT Rating (#PCDATA)>
<!ELEMENT Producer (#PCDATA)>
<!ELEMENT RecordLabel (#PCDATA)>
<!ELEMENT Price (#PCDATA)>


<!ELEMENT Footer (Address, Phone, Email, Website)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT Phone (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Website (#PCDATA)>



<!ATTLIST StoreLogo xmlns CDATA #FIXED "http://www.w3.org/1999/xhtml">
<!ATTLIST CoverArt xmlns CDATA #FIXED "http://www.w3.org/1999/xhtml">
<!ATTLIST img id (storeLogo|songart) #IMPLIED class CDATA #IMPLIED src CDATA #REQUIRED>
<!ATTLIST Song songID CDATA #REQUIRED genre CDATA #REQUIRED length CDATA #REQUIRED>
<!ATTLIST Price currency CDATA #REQUIRED discount CDATA #IMPLIED>

=== karmasta13/Academics/Karmasta Music Store/karmastaMusic.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!--
    Author: Labbi Karmacharya
    Date  : 29 April 2021
-->

<!-- Linking External CSS with the XML document -->
<?xml-stylesheet type="text/css" href="karmastaMusic.css"?>

<!-- Linking External DTD with the XML document -->
<!DOCTYPE Store SYSTEM "karmastaMusic.dtd">

<!-- Linking External Schema with the XML document through the Root Tag -->
<!-- <Store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
    xsi:noNamespaceSchemaLocation="karmastaMusic.xsd" 
    xsi:schemaLocation="https://www.w3schools.com/xml karmastaMusic.xsd"> -->


<!-- Root Tag containing other child elements -->
<Store>

    <!-- Header Tag containing other header elements of the page -->
    <Header>

         <!-- StoreLogo containing image element of the store -->
        <StoreLogo xmlns="http://www.w3.org/1999/xhtml">
            <!-- Image element containing details about the store logo -->
            <img id="storeLogo" src="./image/main_logo.png">Karmasta Music Store logo</img>                                                  
        </StoreLogo>

        <!-- Information regarding karmasta music store -->
        <Name>Karmasta Music Store</Name>
        <Slogan>- Leading the retail industry in digital music commerce -</Slogan>
        <About>
            <![CDATA[
               Established in 1982 A.D., Karmasta Music Store is an industry leader in the music retailing business based on London, UK.
               The store is one of the biggest retail shops for music records, albums, and any thing related to music (as long as it is accessible).                 
            ]]>
        </About>

    </Header>


    <!-- Songs Tag containing other childs elements related to song -->
    <Songs>

        <!-- Song Tag (first element of many) containing other childs elements related to song information -->
        <Song songID="0101" genre="Indie pop" length="00:02:53">

            <!-- CoverArt containing image element of the cover art -->
            <CoverArt xmlns="http://www.w3.org/1999/xhtml">
                <!-- Image element containing details about the cover art -->
                <img class="songart" src="./image/water-melon.png">Watermelon Sugar Coverart</img> 
            </CoverArt>

            <!-- Description of the song based on title, artist, release year, writer, director, and, award -->
            <SongDescription>

                <Title>Watermelon Sugar</Title>
            
                <Artist>Harry Styles</Artist>

                <ReleaseYear>2020</ReleaseYear>
    
                <Writer>Harry Styles</Writer>
                <Writer>Mitch Rowland</Writer>
                <Writer>Tyler Johnson</Writer>
                <Writer>Thomas Hull</Writer>
                
                <Director>Andy McLeod</Director>
            
            </SongDescription>

            <!-- Description of the album based on album, comment, rating, producer, record label, and, price -->
            <AlbumDescription>
    
                <Album>Fine Line</Album>
                <Comment>A collaboration of artists from various genre of the international community.</Comment>
                <Rating>4.8</Rating>

                <Producer>Johnson</Producer>
                <Producer>Kid Harpoon</Producer>
    
                <RecordLabel>Erskine Columbia</RecordLabel>
                
    
                <Price currency="pound" discount="10%">£1.29</Price>

            </AlbumDescription>


        </Song>

        <!-- Song Tag (second element of many) containing other childs elements related to song information -->        
        <Song songID="0110" genre="Pop rock" length="00:03:57">

            <!-- CoverArt containing image element of the cover art -->
            <CoverArt xmlns="http://www.w3.org/1999/xhtml">
                <!-- Image element containing details about the cover art -->
                <img class="songart" src="./image/amnesia.png">Amnesia Coverart</img> 
            </CoverArt>

            <!-- Description of the song based on title, artist, release year, writer, director, and, award -->
            <SongDescription>

                <Title>Amnesia</Title>
            
                <Artist>5 Seconds of Summer</Artist>

                <ReleaseYear>2014</ReleaseYear>
                
    
                <Writer>Michael Biancaniello</Writer>
                <Writer>Louis Biancaniello</Writer>
                <Writer>Benji Madden</Writer>
                <Writer>Joel Madden</Writer>
                <Writer>Sam Wattersk</Writer>

                <Director>Andy McLeod</Director>
            
            </SongDescription>

            <!-- Description of the album based on album, comment, rating, producer, record label, and, price -->
            <AlbumDescription>
    
                <Album>5 Seconds of Summer</Album>
                <Comment>A collaboration of artists from various genre of the international community.</Comment>
                <Rating>4.5</Rating>

                <Producer>M. Biancaniello</Producer>
                <Producer>L. Bianceniello</Producer>
                <Producer>Watters</Producer>
    
                <RecordLabel>Capitol</RecordLabel>
                <RecordLabel>Hi or Hey</RecordLabel>
    
                <Price currency="pound" discount="15%">£1.98</Price>

            </AlbumDescription>

        </Song>


        <!-- Song Tag (third element of many) containing other childs elements related to song information -->        
        <Song songID="0120" genre="Pop" length="00:03:20">

            <!-- CoverArt containing image element of the cover art -->
            <CoverArt xmlns="http://www.w3.org/1999/xhtml">
                <!-- Image element containing details about the cover art -->
                <img class="songart" src="./image/lovely.png">Lovely Coverart</img> 
            </CoverArt>

            <!-- Description of the song based on title, artist, release year, writer, director, and, award -->
            <SongDescription>

                <Title>Lovely</Title>
            
                <Artist>Billie Eilish</Artist>
                <FeaturedArtist>Khalid</FeaturedArtist>

                <ReleaseYear>2018</ReleaseYear>
    
                <Writer>Billie Eilish</Writer>
                <Writer>Finneas</Writer>
                <Writer>Khalid Robinson</Writer>
                
                <Director>Taylor Cohen</Director>
            
            </SongDescription>

            <!-- Description of the album based on album, comment, rating, producer, record label, and, price -->
            <AlbumDescription>
    
                <Album>13 Reasons Why: Season 2</Album>
                <Comment>A collaboration of artists from various genre of the international community.</Comment>
                <Rating>4.6</Rating>

                <Producer>Finneas O'Connell</Producer>
    
                <RecordLabel>Darkroom</RecordLabel>
                <RecordLabel>Interscope</RecordLabel>
    
                <Price currency="pound" discount="10%">£1.58</Price>

            </AlbumDescription>


        </Song>


        <!-- Song Tag (fourth element of many) containing other childs elements related to song information -->
        <Song songID="0130" genre="Folk" length="00:03:18">

            <!-- CoverArt containing image element of the cover art -->
            <CoverArt xmlns="http://www.w3.org/1999/xhtml">
                <!-- Image element containing details about the cover art -->
                <img class="songart" src="./image/Heather.png">Heather Coverart</img> 
            </CoverArt>

            <!-- Description of the song based on title, artist, release year, writer, director, and, award -->
            <SongDescription>

                <Title>Heather</Title>
            
                <Artist>Conan Gray</Artist>

                <ReleaseYear>2020</ReleaseYear>
    
                <Writer>Conan Gray</Writer>

                <Director>Conan Gray</Director>
                <Director>Dilion Matthew</Director>

            </SongDescription>

            <!-- Description of the album based on album, comment, rating, producer, record label, and, price -->
            <AlbumDescription>
    
                <Album>Kid Krow</Album>
                <Comment>Heather” is the tenth track of Conan’s debut album, Kid Krow.</Comment>
                <Rating>4</Rating>

                <Producer>Jam City</Producer>
                <Producer>Dan Nigro</Producer>
    
                <RecordLabel>Republic</RecordLabel>
                <RecordLabel>Island</RecordLabel>
    
                <Price currency="pound" discount="10%">£1.78</Price>

            </AlbumDescription>


        </Song>


        <!-- Song Tag (fifth element of many) containing other childs elements related to song information -->
        <Song songID="0140" genre="Dream Pop" length="00:04:47">

            <!-- CoverArt containing image element of the cover art -->
            <CoverArt xmlns="http://www.w3.org/1999/xhtml">
                <!-- Image element containing details about the cover art -->
                <img class="songart" src="./image/Life.png">Lust for Life Coverart</img> 
            </CoverArt>

            <!-- Description of the song based on title, artist, release year, writer, director, and, award -->
            <SongDescription>

                <Title>Lust for Life</Title>
            
                <Artist>Lana Del Rey</Artist>
                <FeaturedArtist>The Weeknd</FeaturedArtist>

                <ReleaseYear>2017</ReleaseYear>
    
                <Writer>Lana Del Rey</Writer>
                <Writer>Rock Nowels</Writer>
                <Writer>Abel Tesfaye</Writer>
                <Writer>Max Martin</Writer>

                <Director>Clark Jackson</Director>
            
            </SongDescription>
